### ISSUE TITLE
mkdocs doesn't work because of the configuration issues

### ISSUE THREAD

**Issue by chfast** [ethereum/execution-spec-tests#529]
```
mkdocs build --strict
Error: MkDocs encountered an error parsing the configuration file: while constructing a Python object
cannot find module 'material.extensions.emoji' (No module named 'material.extensions')
  in "/home/chfast/Projects/ethereum/execution-spec-tests/mkdocs.yml", line 84, column 20
```

**Comment by charliehirsch78** [comment]
I get a similar error
```
Error: MkDocs encountered an error parsing the configuration file: while constructing a Python object
cannot find module 'material.extensions.emoji' (No module named 'material')
  in "mkdocs.yml", line 126, column 20
```

**Comment by danceratopz** [comment]
Hi @charliehirsch78, could you check whether `mkdocs` material is currently installed?
```
uv pip list | grep material
# ->
# mkdocs-material               9.5.33
# mkdocs-material-extensions    1.3.1
```

If not please make sure that you've installed the extra docs requirements via:
```
uv sync --all-extras
# the following is also possible, but will remove `lint` and `test` extra deps
# uv sync --extra docs
```

Also please make sure you prefix any commands within EEST with `uv run`, for example:
```
uv run mkdocs build --strict
```

**Comment by chfast** [comment]
```
uv run mkdocs build --strict
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /home/chfast/proj/execution-spec-tests/site
INFO    -  DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
             File "/home/chfast/proj/execution-spec-tests/.venv/lib/python3.12/site-packages/trie/__init__.py", line 1, in <module>
               import pkg_resources
             File "/home/chfast/proj/execution-spec-tests/.venv/lib/python3.12/site-packages/pkg_resources/__init__.py", line 103, in <module>
               warnings.warn(
INFO    -  PydanticDeprecatedSince20: `json_encoders` is deprecated. See https://docs.pydantic.dev/2.9/concepts/serialization/#custom-serializers for alternatives. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.9/migration/
             File "/home/chfast/proj/execution-spec-tests/.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 663, in generate_schema
               schema = _add_custom_serialization_from_json_encoders(self._config_wrapper.json_encoders, obj, schema)
             File "/home/chfast/proj/execution-spec-tests/.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 312, in _add_custom_serialization_from_json_encoders
               warnings.warn(
INFO    -  Generating documentation for test cases until Osaka as fill --override-ini filterwarnings=ignore::pytest.PytestAssertRewriteWarning -p pytest_plugins.filler.gen_test_doc.gen_test_doc --gen-docs --gen-docs-target-fork=Prague --until=Osaka --skip-index -m (not blockchain_test_engine) and (not eip_version_check) -s tests
INFO    -  ============================================================================================================ test session starts ============================================================================================================
INFO    -  platform linux -- Python 3.12.7, pytest-7.4.4, pluggy-1.5.0
INFO    -  Generating fixtures for: Frontier, Homestead, Byzantium, Constantinople, ConstantinopleFix, Istanbul, Berlin, London, BerlinToLondonAt5, Paris, Shanghai, ParisToShanghaiAtTime15k, Cancun, ShanghaiToCancunAtTime15k, Prague, CancunToPragueAtTime15k, Osaka
INFO    -  ethereum-spec-evm-resolver 0.0.1
INFO    -  solc: 0.8.24
INFO    -  EELS resolutions file: /home/chfast/proj/execution-spec-tests/eels_resolutions.json
INFO    -  rootdir: /home/chfast/proj/execution-spec-tests
INFO    -  configfile: pytest.ini
INFO    -  plugins: cov-4.1.0, xdist-3.6.1, json-report-1.5.0, custom-report-1.0.1, metadata-3.1.1, html-4.1.1, typeguard-4.3.0
INFO    -  collected 44469 items / 13859 deselected / 30610 selected
INFO    -  INTERNALERROR> Traceback (most recent call last):
INFO    -  INTERNALERROR>   File "/home/chfast/proj/execution-spec-tests/.venv/lib/python3.12/site-packages/_pytest/main.py", line 271, in wrap_session
INFO    -  INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INFO    -  INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
INFO    -  INTERNALERROR>   File "/home/chfast/proj/execution-spec-tests/.venv/lib/python3.12/site-packages/_pytest/main.py", line 324, in _main
INFO    -  INTERNALERROR>     config.hook.pytest_collection(session=session)
INFO    -  INTERNALERROR>   File "/home/chfast/proj/execution-spec-tests/.venv/lib/python3.12/site-packages/pluggy/_hooks.py", line 513, in __call__
INFO    -  INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INFO    -  INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INFO    -  INTERNALERROR>   File "/home/chfast/proj/execution-spec-tests/.venv/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec
INFO    -  INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INFO    -  INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INFO    -  INTERNALERROR>   File "/home/chfast/proj/execution-spec-tests/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 182, in _multicall
INFO    -  INTERNALERROR>     return outcome.get_result()
INFO    -  INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^
INFO    -  INTERNALERROR>   File "/home/chfast/proj/execution-spec-tests/.venv/lib/python3.12/site-packages/pluggy/_result.py", line 100, in get_result
INFO    -  INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INFO    -  INTERNALERROR>   File "/home/chfast/proj/execution-spec-tests/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 103, in _multicall
INFO    -  INTERNALERROR>     res = hook_impl.function(*args)
INFO    -  INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INFO    -  INTERNALERROR>   File "/home/chfast/proj/execution-spec-tests/.venv/lib/python3.12/site-packages/_pytest/main.py", line 335, in pytest_collection
INFO    -  INTERNALERROR>     session.perform_collect()
INFO    -  INTERNALERROR>   File "/home/chfast/proj/execution-spec-tests/.venv/lib/python3.12/site-packages/_pytest/main.py", line 678, in perform_collect
INFO    -  INTERNALERROR>     hook.pytest_collection_modifyitems(
INFO    -  INTERNALERROR>   File "/home/chfast/proj/execution-spec-tests/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 156, in _multicall
INFO    -  INTERNALERROR>     teardown[0].send(outcome)
INFO    -  INTERNALERROR>   File "/home/chfast/proj/execution-spec-tests/src/pytest_plugins/filler/gen_test_doc/gen_test_doc.py", line 259, in pytest_collection_modifyitems
INFO    -  INTERNALERROR>     self.add_global_page_props_to_env()
INFO    -  INTERNALERROR>   File "/home/chfast/proj/execution-spec-tests/src/pytest_plugins/filler/gen_test_doc/gen_test_doc.py", line 340, in add_global_page_props_to_env
INFO    -  INTERNALERROR>     "base_url": self.get_doc_site_base_url(),
INFO    -  INTERNALERROR>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INFO    -  INTERNALERROR>   File "/home/chfast/proj/execution-spec-tests/src/pytest_plugins/filler/gen_test_doc/gen_test_doc.py", line 329, in get_doc_site_base_url
INFO    -  INTERNALERROR>     raise Exception(
INFO    -  INTERNALERROR> Exception: Failed to determine target doc version during strict build (set GEN_TEST_DOC_VERSION env var).
INFO    -  
INFO    -  ====================================================================================================== 13859 deselected, 1 warning in 3.37s ======================================================================================================
ERROR   -  Documentation generation failed (exit: 3, INTERNAL_ERROR).
ERROR   -  Script '/home/chfast/proj/execution-spec-tests/docs/gen_test_case_reference.py' caused SystemExit(<ExitCode.INTERNAL_ERROR: 3>)

Aborted with a BuildError!
```

**Comment by danceratopz** [comment]
Thanks for the heads up @chfast, I updated the [comment above](https://github.com/ethereum/execution-spec-tests/issues/529#issuecomment-2621098451) to remove the `--strict` flag. Another option is to set a dummy version of `GEN_TEST_DOC_VERSION` on the command-line before running `uv run mkdocs build --strict`.
